
# cargo-vet audits file

[audits]

[[trusted.blob-decoder]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.block-buffer]]
criteria = "safe-to-deploy"
user-id = 5059 # Artyom Pavlov (newpavlov)
start = "2019-04-15"
end = "2027-08-24"

[[trusted.chromium-storage-indexeddb]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-29"
end = "2027-08-06"

[[trusted.cpufeatures]]
criteria = "safe-to-deploy"
user-id = 267 # Tony Arcieri (tarcieri)
start = "2021-04-26"
end = "2027-08-24"

[[trusted.crypto-common]]
criteria = "safe-to-deploy"
user-id = 5059 # Artyom Pavlov (newpavlov)
start = "2021-02-10"
end = "2027-08-24"

[[trusted.digest]]
criteria = "safe-to-deploy"
user-id = 267 # Tony Arcieri (tarcieri)
start = "2020-06-10"
end = "2027-08-24"

[[trusted.forensicnomicon]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-05"
end = "2027-08-06"

[[trusted.forensicnomicon-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-06"

[[trusted.forensicnomicon-data]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-06"

[[trusted.generic-array]]
criteria = "safe-to-deploy"
user-id = 5704 # Nova (novacrazy)
start = "2019-04-14"
end = "2027-08-24"

[[trusted.leveldb-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2027-08-24"

[[trusted.protobuf-forensic-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.safe-read]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-15"
end = "2027-08-06"

[[trusted.sha2]]
criteria = "safe-to-deploy"
user-id = 5059 # Artyom Pavlov (newpavlov)
start = "2020-01-06"
end = "2027-08-24"

[[trusted.typenum]]
criteria = "safe-to-deploy"
user-id = 243 # Paho Lurie-Gregg (paholg)
start = "2019-08-25"
end = "2027-08-24"

[[trusted.version_check]]
criteria = "safe-to-deploy"
user-id = 3864 # Sergio Benitez (SergioBenitez)
start = "2019-05-24"
end = "2027-08-24"
